import { HorizontalBox } from "std-widgets.slint";
import { Theme } from "../styles/theme.slint";

export component Badge inherits Rectangle {
    in-out property <string> text: "";
    in-out property <color> bg-color: Theme.infoLight;
    in-out property <color> text-color: Theme.accent-color;
    in-out property <bool> has-dot: false;
    in-out property <color> dot-color: Theme.accent-color;

    height: Theme.heightXs;
    padding-left: Theme.spacingMd;
    padding-right: Theme.spacingMd;
    padding-top: Theme.spacingXs;
    padding-bottom: Theme.spacingXs;
    background: root.bg-color;
    border-radius: Theme.heightXs;

    HorizontalBox {
        spacing: Theme.spacingXs;

        Rectangle {
            width: Theme.iconXs;
            height: Theme.iconXs;
            background: root.dot-color;
            border-radius: Theme.iconXs;
            visible: root.has-dot;
        }

        Text {
            text: root.text;
            color: root.text-color;
            font-size: Theme.fontXs;
            font-weight: Theme.weightMedium;
            vertical-alignment: center;
        }
    }
}
