import { HorizontalBox } from "std-widgets.slint";
import { Theme } from "../styles/theme.slint";

export component Button inherits Rectangle {
    in-out property <string> text: "Button";
    in-out property <color> bg-color: Theme.primary;
    in-out property <color> text-color: #FFFFFF;
    height: 36px;
    background: root.bg-color;
    border-radius: Theme.radiusMd;
    padding-left: 16px;
    padding-right: 16px;
    padding-top: 6px;
    padding-bottom: 6px;

    HorizontalBox {
        spacing: Theme.spacingXs;

        Text {
            text: root.text;
            color: root.text-color;
            font-size: Theme.fontSm;
            font-weight: Theme.weightMedium;
            vertical-alignment: center;
        }
    }
}
