import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { Theme } from "../styles/theme.slint";

export component Card inherits Rectangle {
    in-out property <string> title: "";
    in-out property <string> value: "";
    in-out property <string> subtitle: "";
    in-out property <string> icon-text: "";
    in-out property <color> icon-bg: Theme.accent-color;

    // width: 200px;
    min-height: Theme.heightXl;
    background: Theme.surface-color;
    border-color: Theme.border-color;
    border-width: 1px;
    border-radius: Theme.radiusLg;
    // padding: Theme.spacingMd;

    VerticalBox {
        spacing: Theme.spacingSm;

        HorizontalBox {
            spacing: Theme.spacingSm;

            Rectangle {
                width: Theme.iconXl;
                height: Theme.iconXl;
                background: root.icon-bg;
                border-radius: Theme.radiusMd;

                Text {
                    text: root.icon-text;
                    color: Theme.accent-color;
                    font-size: Theme.fontLg;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                }
            }

            Text {
                text: root.value;
                color: Theme.text-primary-color;
                font-size: Theme.font2xl;
                font-weight: Theme.weightBold;
            }
        }

        Text {
            text: root.title;
            color: Theme.accent-color;
            font-size: Theme.fontSm;
            font-weight: Theme.weightMedium;
        }

        Text {
            text: root.subtitle;
            color: Theme.text-muted-color;
            font-size: Theme.fontXs;
        }
    }
}
