import {
    VerticalBox,
    HorizontalBox,
    StandardTableView,
} from "std-widgets.slint";
import { Theme } from "../styles/theme.slint";



export component MemberDataTable inherits StandardTableView {

    columns: [
        { title:"Id", width: 50px },
        { title:"Name", width: 100px },
        { title:"last Name", width: 180px },
        { title:"Status", width: 80px },
        { title:"Expire Date" }
    ];
}
