import {
    VerticalBox,
    HorizontalBox,
    ComboBox,
    StandardListView,
} from "std-widgets.slint";


export component LeftSidBar inherits Rectangle {
    width: 240px;
    background: #FFFFFF;
    border-color: #E2E8F0;
    border-width: 1px;

    VerticalBox {
        spacing: 20px;
        padding: 10px;

        // App Header
        Rectangle {
            background: transparent;

            HorizontalBox {
                spacing: 10px;

                Rectangle {
                    width: 32px;
                    height: 32px;
                    background: #2563EB;
                    border-radius: 8px;

                    Text {
                        text: "OM";
                        color: #FFFFFF;
                        font-size: 14px;
                        font-weight: 700;
                        horizontal-alignment: center;
                    }
                }

                VerticalBox {
                    spacing: 2px;
                    Text {
                        text: "OpenMember";
                        color: #1E293B;
                        font-size: 16px;
                        font-weight: 600;
                    }

                    Text {
                        text: "Membership Management";
                        color: #64748B;
                        font-size: 11px;
                    }
                }
            }
        }

        // Navigation Links
        Rectangle {

            background: #EFF6FF;
            border-radius: 8px;
            height: 55px;
            HorizontalBox {
                spacing: 20px;

                Image {
                    source: @image-url("../../assets/icons/kanban.svg");
                    vertical-alignment: center;
                    image-fit: contain;
                    width: 25px;
                }

                Text {
                    text: "Dashboard";
                    color: #2563EB;
                    font-size: 14px;
                    font-weight: 500;
                    vertical-alignment: center;
                }
            }
        }

        Rectangle {
            height: 55px;
            HorizontalBox {
                spacing: 20px;

                Image {
                    source: @image-url("../../assets/icons/user-group.svg");
                    vertical-alignment: center;
                    image-fit: contain;
                    width: 25px;
                }

                Text {
                    text: "Members";
                    color: #64748B;
                    font-size: 14px;
                    vertical-alignment: center;
                }
            }
        }

        Rectangle {

            border-radius: 8px;
            height: 55px;

            HorizontalBox {
                spacing: 20px;

                Image {
                    source: @image-url("../../assets/icons/credit-card.svg");
                    vertical-alignment: center;
                    image-fit: contain;
                    width: 25px;
                }

                Text {
                    text: "Plans";
                    color: #64748B;
                    font-size: 14px;
                    vertical-alignment: center;
                }
            }
        }

        Rectangle {

            border-radius: 8px;
            height: 55px;
            HorizontalBox {
                spacing: 20px;

                Image {
                    source: @image-url("../../assets/icons/cog.svg");
                    vertical-alignment: center;
                    image-fit: contain;
                    width: 25px;
                }

                Text {
                    text: "Settings";
                    color: #64748B;
                    font-size: 14px;
                    vertical-alignment: center;
                    horizontal-alignment: left;
                }
            }
        }

        // This consumes all remaining vertical space
        Rectangle {
            vertical-stretch: 1;
        }
        // Footer
        Rectangle {
            background: transparent;
            height: 50px;
            border-color: #E2E8F0;
            border-width: 1px;

            HorizontalBox {
                spacing: 20px;

                Image {
                    source: @image-url("../../assets/icons/circle-check-big.svg");
                    vertical-alignment: center;
                    image-fit: contain;
                    width: 25px;
                }

                Text {
                    text: "v0.0.1";
                    color: #64748B;
                    font-size: 15px;
                    vertical-alignment: center;
                }
            }
        }
    }
}
