import { HorizontalBox } from "std-widgets.slint";
import { Theme } from "../styles/theme.slint";

export component Toast inherits Rectangle {
    property <string> message: "";
    height: Theme.heightLg;
    padding-left: Theme.spacingLg;
    padding-right: Theme.spacingLg;
    padding-top: Theme.spacingSm;
    padding-bottom: Theme.spacingSm;
    background: Theme.text-primary-color;
    border-radius: Theme.radiusMd;

    HorizontalBox {
        spacing: Theme.spacingSm;

        Text {
            text: root.message;
            color: Theme.surface-color;
            font-size: Theme.fontSm;
            vertical-alignment: center;
        }
    }
}
