import { VerticalBox, HorizontalBox, ComboBox } from "std-widgets.slint";
import { Theme } from "../styles/theme.slint";
import { Input } from "./input.slint";
import { Button } from "./button.slint";

export component TopToolbar inherits Rectangle {
    height: Theme.heightXXL;
    // padding: Theme.spacingMd;

    background: Theme.surface-color;
    border-color: Theme.border-color;
    border-width: 1px;

    HorizontalBox {
        spacing: Theme.spacingLg;

        Input {
            placeholder: "Search members...";
            preferred-width: 350px;
        }

        Button {
            text: "+ Add Member";
            bg-color: Theme.accent-color;
            preferred-width: 50px;
        }
    }
}
