export global Typography {
    in-out property <length> fontXs: 10px;
    in-out property <length> fontSm: 11px;
    in-out property <length> fontMd: 13px;
    in-out property <length> fontLg: 14px;
    in-out property <length> fontXl: 16px;
    in-out property <length> font2xl: 24px;
    in-out property <int> weightRegular: 400;
    in-out property <int> weightMedium: 500;
    in-out property <int> weightSemibold: 600;
    in-out property <int> weightBold: 700;
    in-out property <length> leadingTight: 16px;
    in-out property <length> leadingNormal: 20px;
    in-out property <length> leadingRelaxed: 24px;
}
