import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { Card } from "../components/card.slint";
import { Theme } from "../styles/theme.slint";
import { StatusBoard } from "../components/status-board.slint";
import { MembersView } from "./members.slint";
import { MemberDataTable } from "../components/member-data-table.slint";

export component DashboardView inherits VerticalBox {
    spacing: Theme.spacingXl;
    padding: Theme.spacingXl;

    // status board
    StatusBoard {
        height: 50%;
    }

    // member table title
    Rectangle {
        width: 100%;
        height: 12%;
        background: Theme.surface-color;
        border-radius: 15px;
        Text {
            width: 95%;
            height: 100%;
            text: "Newest members";
            horizontal-alignment: start;
            vertical-alignment: center;
        }
    }

    //member tables
  
        MemberDataTable {
        rows: [
            [
                { text:1 },
                { text:"user" },
                { text:"lastName" },
                { text:"Active" },
                { text:"26/09/2026" },
            ]
        ];
    }
}
