import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { Card } from "../components/card.slint";
import { Theme } from "../styles/theme.slint";
import { StatusBoard } from "../components/status-board.slint";
import { MembersView } from "./members.slint";
import { MemberDataTable } from "../components/member-data-table.slint";

export component DashboardView inherits VerticalBox {
    spacing: Theme.spacingXl;
    padding: Theme.spacingXl;

    // status board
    StatusBoard {
        height: 20%;
    }

    // member table title
    Rectangle {
        width: 100%;
        height: 7%;
        background: Theme.surface-color;
        border-radius: 15px;
        Text {
            width: 95%;
            height: 100%;
            text: "Members Table";
            horizontal-alignment: start;
            vertical-alignment: center;
        }
    }

    //member tables
    MemberDataTable { }
}
