import {
    VerticalBox,
    HorizontalBox,
} from "std-widgets.slint";
import { LeftSidBar } from "./components/sidebar-en.slint";
import { MainWindow } from "./components/main_window.slint";
import { Theme } from "./styles/theme.slint";

export component appWindow inherits Window {
    title: "OpenMember - Membership Management";
    width: 1280px;
    height: 800px;
    background: Theme.background;

    callback theme-toggled();

    HorizontalBox {
        spacing: 0px;

        LeftSidBar { }

        MainWindow { }
    }
}
