import {
    VerticalBox,
    HorizontalBox,
} from "std-widgets.slint";
import { LeftSidBar } from "./components/sidebar-en.slint";
import { MainWindow } from "./components/main_window.slint";
import { Theme } from "./styles/theme.slint";

export component AppWindow inherits Window {
    title: "OpenMember - Membership Management";
    width: 1280px;
    height: 800px;
    background: Theme.background;

    callback theme-toggled();
    callback navigate(string);

    HorizontalBox {
        spacing: 0px;

        sidebar := LeftSidBar {
            navigate(view) => {
                main_window.current-view = view;
                root.navigate(view);
            }
        }

        main_window := MainWindow { }
    }
}
